#pragma once

#define WM_DATA_READY		      WM_USER+1011

#define WM_EXTPICMENU_ADD         WM_USER+101 
#define WM_EXTPICMENU_DELETE      WM_USER+102 
#define WM_EXTPICMENU_ADD_POSITON WM_USER+105
#define WM_ZOOMCTRL_LDCLICK		  WM_USER+103
#define WM_ZOOMCTRL_RCLICK		  WM_USER+104

#define ID_MENU_ADD 1001
#define ID_MENU_DELETE 1002
#define ID_MENU_ADD_POSITION 1003

